development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: code_challenge
  pool: 5
  username: root
  password: 
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: code_challenge
  pool: 5
  username: root
  password: 
  

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: code_challenge
  pool: 5
  username: root
  password: 